### ISSUE TITLE
Navigate to the "accept share token" page when app opened by following a share token link

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#101]
`AndroidManifest.xml` already contains the necessary intent-filter, what's missing is invoking the right navigation route when the intent is received. Ideally, this should show the accept share token page with the "token" field pre-filled according to the clicked url.

**Comment by inetic** [comment]
This is partially done, but works only on Androids older than 12.  That is, what we have implemented is what they call a "Web link" which on Androids older than 12 will open the app if installed but on Androids 12 and higher it'll open only in a web browser.

To make it work on all Androids since 6.0 (API level 23) we need to implement a it as a "App link". From what I understand we need to verify somehow that the doman `https://ouisync.net` belongs to eQualitie.

More info here: https://developer.android.com/training/app-links

**Comment by inetic** [comment]
This should now work as of https://github.com/equalitie/ouisync-app/commit/c7a9eb2066e2788d6b84b728e2f687e63ab7c1a4 (ouisync-app) and https://github.com/equalitie/ouisync-web/commit/082937a6a1dca6bd519560d8defa80516c8d8175 (ouisync-web).

Note that it won't work when the app is signed only by the debug key because we (the devs) don't share a common debug keystore.
