### ISSUE TITLE
Migrate to Android 12 (API level 31)

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#137]
When uploading to the play store, there is a new warning:

> Your app currently targets API level 30 and must target at least API level 31 to ensure it is built on the latest APIs optimized for security and performance. [Learn More](https://developer.android.com/google/play/requirements/target-sdk)

**Comment by J-Pabon** [comment]
When the package `mobile_scanner` was added, it required the API level to be upgraded, so it went from 30 to 32, here: 76de0cabde649bc09f63a955de442d5339f1b23c

No issues were detected in regard to other packages or functionalities in the app with this change, but there are a couple of things to double-check, based in the notes from the migration guide:

- Intent filters: If your app contains [activities](https://developer.android.com/guide/components/activities/intro-activities), [services](https://developer.android.com/guide/components/services), or [broadcast receivers](https://developer.android.com/guide/components/broadcasts) that use [intent filters](https://developer.android.com/guide/components/intents-filters#Receiving), you must explicitly declare the [android:exported](https://developer.android.com/guide/topics/manifest/activity-element#exported) attribute for these components.
**Point to check: does it affect the share into OuiSync or the app-link (it should be ok due to the bullet point underneath)? (it looks like it doesn't)**

- [Android App Links verification changes](https://developer.android.com/about/versions/12/behavior-changes-12#android-app-links-verification-changes): When using Android App Link verification, make sure that your intent filters include the BROWSABLE category and support the HTTPS scheme.
**These recommendations are already being followed for opening share tokens (app-link)**

- Hibernation: Apps may be put into hibernation mode if they are not used over a period of time. In hibernation mode your app's runtime permissions and cache are reset, and you can't run jobs or alerts. You can check your [app’s hibernation status](https://developer.android.com/topic/performance/app-hibernation).  
**Point to check: does it affect the background package?**

**Comment by J-Pabon** [comment]
Closed here https://github.com/equalitie/ouisync-app/commit/76de0cabde649bc09f63a955de442d5339f1b23c
