### ISSUE TITLE
Add GUI to add/remove user defined peer addresses

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#140]
A recent addition to ouisync-plugin added added [two new functions](https://github.com/equalitie/ouisync-plugin/commit/5039e3a1af7d4eb660880b67d20124eeaabf1405#diff-2c9ccb144a913cec6e98479688cc3a5c62694d3c2ed2251436784ad84b0a0923R250-R259) for adding and removing endpoints.

The documentation for the input and output is [in their FFI counterparts](https://github.com/equalitie/ouisync-plugin/commit/5039e3a1af7d4eb660880b67d20124eeaabf1405#diff-9088966a21484b6b13b470b8154c9805160211bc3e35df8055a1aa6863f52de2R459-R503)

**Comment by IvanaBlzvc** [comment]
Yeah, maybe. In theory we shouldn't need this, but it's something that may come in handy when debugging.
[20 hr. ago](https://mattermost.equalit.ie/equalitie/pl/oxu3f6fyi3bt3b1ohnapazwnza)

To elaborate, in P2P networks, users need to be able to find each other's IP addresses to connect to each other. In OuiSync we use what's called BitTorrent DHT. This usually works (pretty much always when testing within our team), but last time Sina tested OuiSync with a friend from Iran, they couldn't find each other. In such cases it would be nice if they could communicate their IP addresses through some other channels. On the other hand, instead of implementing this feature we could concentrate on fixing the reason why Sina and his friend couldn't find one another.
