### ISSUE TITLE
Sharing a file into ouisync with locked repository does not work

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#148]
Steps to reproduce:

1. Make sure ouisync is either not running or if it is running has all repos locked
2. Open some other app that allows sharing files (e.g. the file browser)
3. Share a file into ouisync
4. Ouisync shows the "Add file to OuiSync" dialog
5. Clicking "SAVE" does nothing

**Comment by J-Pabon** [comment]
The issue here is that when trying to share a file into **OuiSync** when there are not repositories, or when the repository is locked, shows a snack bar with a message telling the use this and what to do; but the snack bar is behind the bottom sheet modal with the **CANCEL** and **SAVE** buttons, so it is not visible.

I am thinking on replacing the snack bar with a dialog to avoid this issue, and potentially let the user create a repo or unlocked it from this dialog (still don't know how good that would be)

**Comment by J-Pabon** [comment]
Closed here e07eb4c77cd1824fbd1e5502dca2ec382969fc5f
![share_into_ouisync_01](https://user-images.githubusercontent.com/13749449/201832705-6f97be14-671c-40e4-8d8e-461d066ad796.png)
![share_into_ouisync_02](https://user-images.githubusercontent.com/13749449/201832716-8fb0dc5e-1290-4dd8-88ba-30cca1401990.png)
![share_into_ouisync_03](https://user-images.githubusercontent.com/13749449/201832732-45304124-44aa-456c-b224-3a8dcfb7a888.png)
![share_into_ouisync_04](https://user-images.githubusercontent.com/13749449/201832739-2a239a11-fcda-464a-a55c-fa33e520ce1c.png)
