### ISSUE TITLE
Windows: the ouisync library should be built automatically and as part of building the ouisync-plugin

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#152]
Currently we build it manually inside `.github/workflows/windows.yml`

**Comment by IvanaBlzvc** [comment]
@J-Pabon assigning to you as you are working on it already.

**Comment by IvanaBlzvc** [comment]
To elaborate, in P2P networks, users need to be able to find each other's IP addresses to connect to each other. In OuiSync we use what's called BitTorrent DHT. This usually works (pretty much always when testing within our team), but last time Sina tested OuiSync with a friend from xxxx, they couldn't find each other. In such cases it would be nice if they could communicate their IP addresses through some other channels. On the other hand, instead of implementing this feature we could concentrate on fixing the reason why Sina and his friend couldn't find one another.

**Comment by J-Pabon** [comment]
> From MM, https://mattermost.equalit.ie/equalitie/pl/g1mdt18nuigzmniq681kfhdaqa "To elaborate, in P2P networks, users need to be able to find each other's IP addresses to connect to each other. In OuiSync we use what's called BitTorrent DHT. This usually works (pretty much always when testing within our team), but last time Sina tested OuiSync with a friend from xxxx, they couldn't find each other. In such cases it would be nice if they could communicate their IP addresses through some other channels. On the other hand, instead of implementing this feature we could concentrate on fixing the reason why Sina and his friend couldn't find one another."

@IvanaBlzvc this is not related with this issue. We need to find the correct one or create it (I think we don't have one for this functionality)

**Comment by J-Pabon** [comment]
Closed here c8edf750530297177005d5b6f567d00e52965918
