### ISSUE TITLE
Server storage - to implement an opt-out option?

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#230]
After chatting on MM today, there is a question of what the server storage will look like for the user. Will user have to perform some action to enable it?  Or will it be enabled for every user by default? 

Or is it better to have the opt out option for users, to avoid the situation where they didn't enabled it and don't understand why they can't sync?

Tio Use this ticket for discussion?

**Comment by IvanaBlzvc** [comment]
In today's stand up we talked about it and yes, there will be an opt out for the user to say - 'I don't want this repository to be stored on your server'.  
Keeping open to test when developed.

**Comment by IvanaBlzvc** [comment]
I imagien the opt out will be at th elevel of repository and  not the level of the app.  I may not want to store some repositories on the server, and I may want to store others on the server. 

So.. My question is: if I want to share a repo with my firend, and I want to do it via a server, when do I choose this option?  Because - what happens if my friend wants to import the link I send them, but doesn't want to sync with the server? 

Is that a possible scenario?  Or is only the 'owner'  or creator of a repo the one who is able to decide if a particular repo will be stored on the server and synced via a server, or not?

**Comment by madadam** [comment]
We have multiple options when it comes to who can enable the server storage:

1. Only the owner
2. Only the people who were given explicit permission by the owner
3. Anyone with write access
4. Anyone with any access (blind, read, write)

There might be other options besides these. 

Out of those, number 4 is the easiest to implement because the server only needs blind access to create the mirror and so anyone with a blind access can send their blind token to the server and the server can start syncing the repo. Any other option requires some kind of access control on the server. Out of those, number 3 is probably the second easiest to implement because the access control there is based only on the share token. All the other options requires some additional permission checking mechanism to be implemented.

**Comment by madadam** [comment]
Related library issue: https://github.com/equalitie/ouisync/issues/130

**Comment by IvanaBlzvc** [comment]
D's comments in MM (peter, d direct message, 20 feb 2024) - there should be an option within the UI to opt-in, and documentation to e updated accordingly)

**Comment by IvanaBlzvc** [comment]
An additional quesiton: should the user be able to opt out only at the time of repo creation (in which case the repo doesn't get created on the server) or should that option be available later as well, when repo already exists on the cache server, but the user changes their mind about it?

**Comment by IvanaBlzvc** [comment]
when this is implemented, to update the privacy notice and the FAQs

**Comment by IvanaBlzvc** [comment]
Redmine 26396
