### ISSUE TITLE
Hitting enter button when Unlock screen shown allows user to enter the settings screen without password

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#283]
Steps to reproduce: 

- Create a repository with read/write permissions, and local password,  then lock it. 
- On the repository screen, bring the focus to the repository name by using the tab key on the windows keyboard. Repository is now showing as blind.  
- when repository name is highlighted, hit enter 
- this action opens the Unlock screen.  
- Without doing anything else, just hit enter when the Unlock screen is displayed. 
Expected results: 
- the password dialog comes up and th euser is required to enter the password to proceed
Actual results: 
- repository settings screen is disaplyed for the user (even though they did not enter the required password to unlock the repo)
[Focus.odt](https://github.com/equalitie/ouisync-app/files/12513243/Focus.odt)

**Comment by J-Pabon** [comment]
A couple of comments (from the attached document):

- The different highlighting are as expected: one is for the focused widget using the tab navigation (darker), the other for the mouse over event (lighter).

That is also the reason why tapping ENTER only works for the dark highlighting: the widget is selected, while the light version only means the mouse is over the widget, not that is selected.

- The unexpected navigation to the settings screen, instead of the unlock dialog was fixed: in this case the behavior was due to the icon for the settings getting the focus when navigating from the list of repositories using the TAB key to select the repository, then using ENTER.

The correct behavior is: when navigating from the list of repositories, if the repository is locked, the unlock button is given the focus automatically; if the repository is already unlocked, then the FAB is given the focus.

**Comment by IvanaBlzvc** [comment]
retested with 0.7.5 = OK
