### ISSUE TITLE
Can this app keep folders synced between two android phones?

### ISSUE THREAD

**Issue by retorquere** [equalitie/ouisync-app#344]
I'm looking to mirror my camera roll between two phones, is this something ouisync can do?

**Comment by inetic** [comment]
If you're looking for a solution where one app writes the camera roll onto the file system and another app reads and syncs it with another device, then unfortunately this can't be done directly with Ouisync on Android. The reason is that Ouisync stores the files and directory structure into an encrypted MySql database. That is, not as files and folders on the file system.

On Android, the interface to view this directory structure is this app, and to allow other apps to view the files we use the Android's [`AbstractFileProvider`](https://github.com/equalitie/ouisync-app/wiki/Exposing-files-to-other-applications#android) machinery. The situation is slightly different on Linux and Windows, but you did not mention those so I won't go into details.

If you were to do this programmatically, where you'd modify the source of the app that captures the camera roll, you could modify it such that it wouldn't write it to the file system, but would do so directly to Ouisync. This could be done using the [Kotlin or Dart API](https://github.com/equalitie/ouisync/tree/master/bindings). Although doing so might be an overkill, and perhaps all you need is a direct write into a socket and receive it on the other end. Depends on what transport properties you require.

**Comment by retorquere** [comment]
That's indeed what I'm looking for, and ouisync seemed easier to set up than syncthing.

**Comment by inetic** [comment]
I'm going to close this issue but feel free to reopen if you have more questions.
