### ISSUE TITLE
High latency start

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#44]
When starting the app, first a blank screen is appears which takes about 4 seconds before the screen with repositories is shown. During this time I see a lot of messages like this:

```
02-08 17:21:05.967 28770 28770 I ViewRootImpl@855e5e[MainActivity]: [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@345026a  isViewVisible: true
02-08 17:21:05.968 28770 28770 I ViewRootImpl@855e5e[MainActivity]: [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@345026a  isViewVisible: true
02-08 17:21:05.969 28770 28770 I ViewRootImpl@855e5e[MainActivity]: [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@345026a  isViewVisible: true
02-08 17:21:05.984 28770 28770 I ViewRootImpl@855e5e[MainActivity]: [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@345026a  isViewVisible: true
02-08 17:21:06.001 28770 28770 I ViewRootImpl@855e5e[MainActivity]: [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@345026a  isViewVisible: true
...
02-08 17:21:10.160 28770 28770 I ViewRootImpl@855e5e[MainActivity]: [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@345026a  isViewVisible: true
```

I am not entirely sure, but I think this may have started doing somewhere between commits 11a43f7 and 98d201c.

**Comment by J-Pabon** [comment]
@inetic is your phone a Samsung?

https://github.com/flutter/flutter/issues/93668#issue-1053885329

I removed the lines referenced in this comment (https://github.com/flutter/flutter/issues/93668#issuecomment-1019928100) some time ago, as the splash screen parameter was deprecated (Maybe you remember this week in the standup, when you created this issue, I mentioned it as maybe related -can’t say because I knew something, just made sense for being at start up)

Also, this would explain why I never saw this, nor noticed the unusual long time loading the app:  the phone I use for debuging is a Nokia.

**Comment by inetic** [comment]
Yeah it's on Samsung. I tried to add the lines

```
<meta-data
    android:name="io.flutter.embedding.android.SplashScreenDrawable"
    android:resource="@drawable/launch_background"
/>
```

to the AndroidManifest.xml and the log output disappeared. The ~4 seconds latency in starting remained however. But then I tried to create a simple test program with `flutter create test` and that had the same latency and log output problems. So closing this as it appears it's related to Flutter.
